confirm-before-quit = false

padding-x = 10
padding-y = [5, 5]

# Colors (One Half Dark)

[cursor]
shape = 'underline'
blinking = true
blinking-interval = 600

[colors] 
background = '#282C34'
foreground = '#DCDFE4'

cursor = '#A3B3CC'

black = '#282c34'
red = '#E06C75'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#56B6C2'
white = '#DCDFE4'

# Dim colors
dim-black = '#282C34'
dim-red = '#E06C75'
dim-green = '#98C379'
dim-yellow = '#E5C07B'
dim-blue = '#61AFEF'
dim-magenta = '#C678DD'
dim-cyan = '#56B6C2'
dim-white = '#DCDFE4'

# Light colors
light-black = '#282C34'
light-red = '#E06C75'
light-green = '#98C379'
light-yellow = '#E5C07B'
light-blue = '#61AFEF'
light-magenta = '#C678DD'
light-cyan = '#56B6C2'
light-white = '#DCDFE4'

[fonts]
size = 14
features = []
symbol-map = []

[fonts.regular]
family = "JetBrainsMono Nerd Font"
style = "Normal"
weight = 400

[fonts.bold]
family = "JetBrainsMono Nerd Font"
style = "Normal"
weight = 800

[fonts.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
weight = 400

[fonts.bold-italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
weight = 800

[shell]
program = "/bin/zsh"
args = ["-l"]

[platform]
windows.shell.program = "pwsh"
windows.shell.args = ["-l"]

[style]
theme = "tokyonight"
